version: 2
updates:
  # NuGet package updates
  - package-ecosystem: 'nuget'
    directory: './src'
    schedule:
      interval: 'daily'

  # GitHub Actions updates
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
