name: .NET Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  solutionPath: 'src/ShoppingCart.sln'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ----- Checkout source -----
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for git versioning logic

      # ----- Install .NET SDK -----
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # or 7.0.x / 6.0.x etc.

      # ----- Restore packages -----
      - name: Restore dependencies
        run: dotnet restore ${{ env.solutionPath }}

      # ----- Build the solution -----
      - name: Build
        run: dotnet build ${{ env.solutionPath }} --configuration Release --no-restore

      # ----- Generate SBOM -----
      - name: Generate XML SBOM
        uses: CycloneDX/gh-dotnet-generate-sbom@v1
        with:
          path: ./${{ env.solutionPath }}

      # ----- Upload SBOM -----
      - name: Upload XML SBOM
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          protocol: 'http'
          serverHostname: '4.180.58.159'
          port: '8080'
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          project: '3fccfcda-2cab-40f5-bda0-ba6b43d5d1bd'
          bomFilename: 'bom.xml'
          autoCreate: true

      # ----- Sonar Qube -----
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          New-Item -Path ${{ runner.temp }}/scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path ${{ runner.temp }}/scanner

      - name: Build and analyze
        shell: pwsh
        run: |
          ${{ runner.temp }}/scanner/dotnet-sonarscanner begin /k:"kpo-shoppingCart" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build ${{ env.solutionPath }}
          ${{ runner.temp }}/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      # ----- Install ReSharper, Inspect and Analyze code -----
      - name: Download ReSharper Command Line Tools
        run: |
          dotnet new tool-manifest
          dotnet tool install JetBrains.ReSharper.GlobalTools
          # In the build script
          dotnet tool restore

      - name: Inspect code
        run: dotnet tool run jb inspectcode ${{ env.solutionPath }} -o=./inspectcode-result.json

      - name: Analyze code
        shell: pwsh
        run: ./.github/workflows/scripts/analyzeInspectCodeOutput.ps1 -inspectOutputPath ./inspectcode-result.json

      # ----- Run tests -----
      - name: Test with the dotnet CLI
        run: dotnet test ${{ env.solutionPath }} --no-build --no-restore

      # ----- Git Version -----
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.2.0
        with:
          versionSpec: '6.4.x'

      - name: Determine Version
        id: version_step # step id used as a reference for output values
        uses: gittools/actions/gitversion/execute@v4.2.0
